//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelFitness
{
    using System;
    using System.Collections.Generic;
    
    public partial class system_Component
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public system_Component()
        {
            this.User_Role_Access = new HashSet<User_Role_Access>();
        }
    
        public int system_Component_Id { get; set; }
        public string system_Component_Name { get; set; }
        public string system_Component_Description { get; set; }
        public string system_Component_Date { get; set; }
        public string system_Component_Update_Date { get; set; }
        public byte system_ComponentPart_State { get; set; }
        public Nullable<int> system_Component_Part_Level { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Role_Access> User_Role_Access { get; set; }
    }
}
