//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelFitness
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Role_Access
    {
        public int PK_user_Role_Access_Id { get; set; }
        public Nullable<int> FK_user_Role_Id { get; set; }
        public Nullable<int> FK_system_Part_Id { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual system_Component system_Component { get; set; }
    }
}
