//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelFitness
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AuthUsers
    {
        public int PK_users_Id { get; set; }
        public string user_Auth_UserName { get; set; }
        public string user_Auth_Password { get; set; }
        public string user_Auth_PasswordHin { get; set; }
        public Nullable<byte> user_Auth_Status { get; set; }
        public string user_Auth_CreateUserTime { get; set; }
        public Nullable<int> FK_user_Auth_role_Id { get; set; }
        public string users_FirstName { get; set; }
        public string users_LastName { get; set; }
    }
}
