//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelFitness
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_members
    {
        public int PK_users_Id { get; set; }
        public string FullName { get; set; }
        public string users_PhoneNumber { get; set; }
        public string users_Address { get; set; }
        public string users_CreateUserTime { get; set; }
        public Nullable<byte> users_Status { get; set; }
        public string users_Description { get; set; }
        public Nullable<double> usersInfoFitness_Height { get; set; }
        public Nullable<double> usersInfoFitness_Weight { get; set; }
        public Nullable<double> usersInfoFitness_WaistMeasure { get; set; }
        public string usersInfoFitness_StartDate { get; set; }
        public string usersInfoFitness_EndDate { get; set; }
        public string usersInfoFitness_BirthdayDate { get; set; }
        public Nullable<int> usersInfoFitness_Age { get; set; }
        public Nullable<decimal> usersInfoFitness_MonthlyAmount { get; set; }
        public Nullable<double> usersInfoFitness_BMI { get; set; }
        public Nullable<double> usersInfoFitness_BMR { get; set; }
        public string usersInfoFitness_CreateUserTime { get; set; }
        public string users_LastName { get; set; }
        public string users_FirstName { get; set; }
        public Nullable<byte> usersInfoFitness_exerciesLevel { get; set; }
        public string usersInfoFitness_exerciesLevelStr { get; set; }
    }
}
